# edit and copy to ~/.config/autodesk/config.yaml
enabled: true
credentials_path: '~/.config/autodesk/client_secret.json'  # google api credentials
token_path: '~/.config/autodesk/token.pickle'  # google api token
timezone: 'Australia/Sydney'  # timezone of the machine running cron
calendar_id: 'name@domain.xyz'  # name of the calendar to fetch
end_threshold_seconds: 600  # if previous meeting ends within 600 seconds of this one, don't raise
max_meeting_standing_time: 3600 # don't raise if meeting is longer than this
trigger_offset_seconds: 60  # how many seconds before the start of the meeting should the desk raise
cron_delimiter: '# Desk Actions'  # replace everything below this line in cron with the updated jobs
trigger_script: 'python /home/pi/autodesk/trigger.py'  # cron command
cron_backup_path: '/tmp/crontab.bak'  # where to backup cron file for editing
ignore_times: ['12:00'] # don't raise for any meeting starting at this time
